# Features extraction code

## Requirements

In [43]:
!pip3 install pandas openpyxl numpy opensmile torch torchaudio torchcodec

Requirement already satisfied: pandas in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: openpyxl in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (2.4.2)
Requirement already satisfied: opensmile in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (2.6.0)
Requirement already satisfied: torch in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (2.10.0)
Requirement already satisfied: torchaudio in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (2.10.0)
Requirement already satisfied: torchcodec in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (0.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: audobject>=0.6.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from opensmile) (0.7.12)
Requirement already satisfied: audinterface>=0.7.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from opensmile) (1.3.1)
Requirement already satisfied: filelock in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (3.25.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (82.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (2026.2.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from cuda-bindings==12.9.4->torch) (1.4.0)
Requirement already satisfied: audeer>=2.1.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audinterface>=0.7.0->opensmile) (2.4.0)
Requirement already satisfied: audformat<2.0.0,>=1.0.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audinterface>=0.7.0->opensmile) (1.3.4)
Requirement already satisfied: audiofile>=1.3.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audinterface>=0.7.0->opensmile) (1.6.0)
Requirement already satisfied: audmath>=1.4.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audinterface>=0.7.0->opensmile) (1.4.4)
Requirement already satisfied: audresample<2.0.0,>=1.1.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audinterface>=0.7.0->opensmile) (1.3.5)
Requirement already satisfied: asttokens>=2.0.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audobject>=0.6.1->opensmile) (3.0.1)
Requirement already satisfied: importlib-metadata>=4.8.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audobject>=0.6.1->opensmile) (8.7.1)
Requirement already satisfied: oyaml in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audobject>=0.6.1->opensmile) (1.0)
Requirement already satisfied: packaging in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audobject>=0.6.1->opensmile) (26.0)
Requirement already satisfied: six>=1.5 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: tqdm in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audeer>=2.1.1->audinterface>=0.7.0->opensmile) (4.67.3)
Requirement already satisfied: iso639-lang in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audformat<2.0.0,>=1.0.1->audinterface>=0.7.0->opensmile) (2.6.3)
Requirement already satisfied: iso3166 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audformat<2.0.0,>=1.0.1->audinterface>=0.7.0->opensmile) (2.1.1)
Requirement already satisfied: pyarrow>=10.0.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audformat<2.0.0,>=1.0.1->audinterface>=0.7.0->opensmile) (23.0.1)
Requirement already satisfied: pyyaml>=5.4.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audformat<2.0.0,>=1.0.1->audinterface>=0.7.0->opensmile) (6.0.3)
Requirement already satisfied: soundfile>=0.12.1 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from audiofile>=1.3.0->audinterface>=0.7.0->opensmile) (0.13.1)
Requirement already satisfied: zipp>=3.20 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from importlib-metadata>=4.8.0->audobject>=0.6.1->opensmile) (3.23.0)
Requirement already satisfied: cffi>=1.0 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from soundfile>=0.12.1->audiofile>=1.3.0->audinterface>=0.7.0->opensmile) (2.0.0)
Requirement already satisfied: pycparser in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from cffi>=1.0->soundfile>=0.12.1->audiofile>=1.3.0->audinterface>=0.7.0->opensmile) (3.0)

## Imports

In [38]:
import pandas as pd
import openpyxl
import json
import statistics
import numpy as np
import opensmile
import torch
import torchaudio

## Dataframe creation and general variables

In [11]:
features_df = pd.read_excel("../extracted_features/extracted_features.xlsx")

data_path = "../data/"
valid_participants = features_df["participant_id"].unique()

features_df

,participant_id,gender,age,condition,perceived_topic_intimacy,personal_discomfort,revealing_personal_information
0,4,M,23,1,5,1.571,1.25
1,4,M,23,2,4,1.000,1.00
2,5,M,20,1,3,1.143,1.25
3,5,M,20,2,4,2.429,2.00
4,6,F,27,1,4,1.143,1.00
5,6,F,27,2,3,1.286,2.75
6,7,F,21,1,1,1.000,1.75
7,7,F,21,2,3,1.000,1.75
8,9,M,26,1,4,1.714,2.00
9,9,M,26,2,2,1.286,1.50
10,11,F,28,1,2,1.000,1.00
11,11,F,28,2,4,1.286,2.25
12,12,F,19,1,2,1.143,3.25
13,12,F,19,2,5,2.571,5.00
14,13,F,19,1,2,1.143,1.50
15,13,F,19,2,5,2.429,3.25
16,14,F,24,1,4,1.000,3.00
17,14,F,24,2,3,1.000,3.00
18,15,M,29,1,3,1.143,1.50
19,15,M,29,2,4,2.143,1.00
20,16,F,24,1,3,1.286,1.75
21,16,F,24,2,5,2.286,3.25
22,17,M,19,1,3,1.286,1.00
23,17,M,19,2,4,2.571,3.00
24,18,M,32,1,2,1.714,1.75
25,18,M,32,2,4,2.571,2.25
26,19,M,35,1,1,1.000,1.25
27,19,M,35,2,4,1.286,1.25
28,20,M,18,1,4,1.143,2.25
29,20,M,18,2,2,2.143,4.00
30,21,M,18,1,1,1.000,2.50
31,21,M,18,2,4,2.429,3.75
32,22,F,23,1,4,1.000,2.50
33,22,F,23,2,5,1.286,3.25
34,23,M,21,1,3,1.000,2.25
35,23,M,21,2,3,1.429,3.00
36,25,F,27,1,3,1.571,1.50
37,25,F,27,2,4,3.143,3.25
38,26,F,25,1,4,1.571,1.25
39,26,F,25,2,2,1.143,2.25
40,28,M,26,1,4,1.571,2.00
41,28,M,26,2,3,2.429,3.25
42,29,M,26,1,2,1.286,1.00
43,29,M,26,2,4,1.000,1.00
44,30,F,22,1,3,1.571,1.75
45,30,F,22,2,2,1.286,1.50
46,31,F,25,1,1,1.000,1.75
47,31,F,25,2,4,2.429,3.50
48,32,F,36,1,3,1.429,2.75
49,32,F,36,2,5,3.714,4.50

## General features

### Activity time

In [17]:
activity_time_list = []

for participant in valid_participants:
    for condition in ["c1", "c2"]:
        stroke_file_path = data_path + "p" + str(participant) + "/drawing_data/strokes_" + condition + ".json"
        with open(stroke_file_path, "r") as file:
            data = json.load(file)
        activity_time_list.append(round(data["activity_time"], 2))

features_df["activity_time"] = activity_time_list

## Drawing dynamics features

### Stroke count

In [19]:
stroke_count_list = []

for participant in valid_participants:
    for condition in ["c1", "c2"]:
        stroke_file_path = data_path + "p" + str(participant) + "/drawing_data/strokes_" + condition + ".json"
        with open(stroke_file_path, "r") as file:
            data = json.load(file)
        stroke_count_list.append(len(data["strokes"]) + len(data["undone_erased_strokes"]))

features_df["stroke_count"] = stroke_count_list

### Stroke length (total, mean, std)

In [21]:
def compute_stroke_length(stroke_points):
        point_coordinates = np.array(stroke_points)

        # Differences between consecutive points
        diffs = np.diff(point_coordinates, axis=0)

        # Euclidian distances between consecutive points
        euclidian_distances = np.sqrt((diffs ** 2).sum(axis=1))

        # Sum all the distances between each consecutive points of the stroke
        total_stroke_length = euclidian_distances.sum()

        return total_stroke_length

In [24]:
stroke_total_length_list = []
stroke_mean_length_list = []
stroke_std_length_list = []

for participant in valid_participants:
    for condition in ["c1", "c2"]:
        stroke_file_path = data_path + "p" + str(participant) + "/drawing_data/strokes_" + condition + ".json"
        with open(stroke_file_path, "r") as file:
            data = json.load(file)

        # Extract length of each stroke of participant
        stroke_length_array = []
        for stroke in (data["strokes"] + data["undone_erased_strokes"]):
            stroke_length_array.append(compute_stroke_length(stroke["points"]))

        # Compute total, mean, and std stroke length
        stroke_total_length_list.append(round(sum(stroke_length_array), 2))
        stroke_mean_length_list.append(round(statistics.mean(stroke_length_array), 2))
        stroke_std_length_list.append(round(statistics.stdev(stroke_length_array), 2))

features_df["stroke_total_length"] = stroke_total_length_list
features_df["stroke_mean_length"] = stroke_mean_length_list
features_df["stroke_std_length"] = stroke_std_length_list

### Stroke speed and acceleration (mean and std)

### Stroke pressure (mean, std, slope over time?)

### Temporal drawing behavior

### Editing behavior

## Drawing production features

## Speech dynamics features

In [39]:
# Initialize openSMILE with eGeMAPS functional features
smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.eGeMAPSv02,
    feature_level=opensmile.FeatureLevel.Functionals,
)

features_of_interest = [
    "F0semitoneFrom27.5Hz_sma3nz_amean",
    "F0semitoneFrom27.5Hz_sma3nz_stddevNorm",
    "F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2",
    "loudness_sma3_amean",
    "loudness_sma3_stddevNorm",
    "jitterLocal_sma3nz_amean",
    "shimmerLocaldB_sma3nz_amean",
    "HNRdBACF_sma3nz_amean",
]

In [44]:
# Load Silero VAD
model, utils = torch.hub.load(
    repo_or_dir='snakers4/silero-vad',
    model='silero_vad',
    force_reload=False
)

(get_speech_timestamps,
 save_audio,
 read_audio,
 VADIterator,
 collect_chunks) = utils


def compute_speech_time(audio_path):
    wav, sr = torchaudio.load(audio_path)

    # Ensure mono
    if wav.shape[0] > 1:
        wav = torch.mean(wav, dim=0, keepdim=True)

    # Resample from 44.1 KHz to 16 KHz
    if sr != 16000:
        wav = torchaudio.functional.resample(wav, sr, 16000)
        sr = 16000

    speech_timestamps = get_speech_timestamps(wav.squeeze(0), model, sampling_rate=sr)

    total_speech_time = sum((ts['end'] - ts['start']) for ts in speech_timestamps) / sr

    return total_speech_time

Using cache found in /home/maure/.cache/torch/hub/snakers4_silero-vad_master

In [45]:
# Create storage dictionary
opensmile_data = {feat: [] for feat in features_of_interest}
speech_time_list = []

for participant in valid_participants:
    for condition in ["c1", "c2"]:

        audio_file_path = data_path + "p" + str(participant) + "/audio_data/p" + str(participant) + condition + "_copy.wav"

        # Extract opensmile features
        print("Processing participant:", str(participant), "- condition:", condition)
        result = smile.process_file(audio_file_path)

        # opensmile result is a pandas dataframe (1 row for functionals)
        for feature in features_of_interest:
            value = result[feature].values[0]
            opensmile_data[feature].append(value)

        # Compute speech time
        speech_time = compute_speech_time(audio_file_path)
        speech_time_list.append(speech_time)

# Add opensmile features to dataframe
for feature in features_of_interest:
    features_df[feature] = opensmile_data[feature]

# Add speech time to dataframe
features_df["total_speech_time"] = speech_time_list

# Add speech ratio to dataframe
features_df["speech_ratio"] = (features_df["total_speech_time"] / features_df["activity_time"])

Processing participant: 4 - condition: c1
Processing participant: 4 - condition: c2
Processing participant: 5 - condition: c1
Processing participant: 5 - condition: c2
Processing participant: 6 - condition: c1
Processing participant: 6 - condition: c2
Processing participant: 7 - condition: c1
Processing participant: 7 - condition: c2
Processing participant: 9 - condition: c1
Processing participant: 9 - condition: c2
Processing participant: 11 - condition: c1
Processing participant: 11 - condition: c2
Processing participant: 12 - condition: c1
Processing participant: 12 - condition: c2
Processing participant: 13 - condition: c1
Processing participant: 13 - condition: c2
Processing participant: 14 - condition: c1
Processing participant: 14 - condition: c2
Processing participant: 15 - condition: c1
Processing participant: 15 - condition: c2
Processing participant: 16 - condition: c1
Processing participant: 16 - condition: c2
Processing participant: 17 - condition: c1
Processing participant: 17 - condition: c2
Processing participant: 18 - condition: c1
Processing participant: 18 - condition: c2
Processing participant: 19 - condition: c1
Processing participant: 19 - condition: c2
Processing participant: 20 - condition: c1
Processing participant: 20 - condition: c2
Processing participant: 21 - condition: c1
Processing participant: 21 - condition: c2
Processing participant: 22 - condition: c1
Processing participant: 22 - condition: c2
Processing participant: 23 - condition: c1
Processing participant: 23 - condition: c2
Processing participant: 25 - condition: c1
Processing participant: 25 - condition: c2
Processing participant: 26 - condition: c1
Processing participant: 26 - condition: c2
Processing participant: 28 - condition: c1
Processing participant: 28 - condition: c2
Processing participant: 29 - condition: c1
Processing participant: 29 - condition: c2
Processing participant: 30 - condition: c1
Processing participant: 30 - condition: c2
Processing participant: 31 - condition: c1
Processing participant: 31 - condition: c2
Processing participant: 32 - condition: c1
Processing participant: 32 - condition: c2

KeyError: 'activity_duration'

## Speech production features (transcript)

## Display and save final features dataframe

In [47]:
features_df.to_excel("../extracted_features/extracted_features_final.xlsx", index=False)

features_df

,participant_id,gender,age,condition,perceived_topic_intimacy,personal_discomfort,revealing_personal_information,activity_time,stroke_count,stroke_total_length,...,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,loudness_sma3_amean,loudness_sma3_stddevNorm,jitterLocal_sma3nz_amean,shimmerLocaldB_sma3nz_amean,HNRdBACF_sma3nz_amean,total_speech_time,speech_ratio
0,4,M,23,1,5,1.571,1.25,1209.19,464,32406.17,...,22.730339,0.206271,6.394100,0.720653,0.784576,0.052364,1.437832,0.721781,265.572000,0.219628
1,4,M,23,2,4,1.000,1.00,1118.29,311,31294.04,...,22.718616,0.196353,5.203865,0.788069,0.791739,0.045662,1.446904,0.573326,436.644000,0.390457
2,5,M,20,1,3,1.143,1.25,976.01,483,251620.84,...,25.529953,0.167680,4.161392,1.161250,0.698495,0.040078,1.207340,3.940016,441.841250,0.452702
3,5,M,20,2,4,2.429,2.00,1007.23,318,207701.98,...,26.459944,0.172920,5.268013,1.366651,0.710858,0.043603,1.250476,3.951181,538.496000,0.534631
4,6,F,27,1,4,1.143,1.00,849.10,115,29558.12,...,30.298620,0.264035,14.135735,0.593465,0.661590,0.043968,1.169680,4.194973,237.840000,0.280108
5,6,F,27,2,3,1.286,2.75,556.19,137,15112.46,...,30.457277,0.251553,13.270615,0.584809,0.619730,0.041284,1.134220,4.613741,160.780000,0.289074
6,7,F,21,1,1,1.000,1.75,679.11,157,32312.35,...,32.126938,0.183674,3.902401,0.933588,0.607276,0.040284,1.065604,7.012737,348.904000,0.513767
7,7,F,21,2,3,1.000,1.75,508.09,105,18139.80,...,32.114250,0.195904,4.463032,0.878542,0.591010,0.042389,1.115764,6.872468,263.025812,0.517676
8,9,M,26,1,4,1.714,2.00,796.32,106,149419.08,...,23.867699,0.158444,2.880827,0.736282,0.622273,0.036094,1.220165,3.156016,228.916000,0.287467
9,9,M,26,2,2,1.286,1.50,564.09,83,31562.58,...,24.051962,0.174025,3.338686,0.769878,0.652640,0.036670,1.237442,3.040056,154.428000,0.273765
10,11,F,28,1,2,1.000,1.00,967.74,355,28442.45,...,27.830435,0.305261,16.925436,0.528997,0.720124,0.051317,1.181761,3.651625,194.636000,0.201124
11,11,F,28,2,4,1.286,2.25,959.02,472,24608.77,...,26.670454,0.300407,15.576859,0.478531,0.704551,0.055036,1.219624,2.940307,263.696000,0.274964
12,12,F,19,1,2,1.143,3.25,857.95,314,25720.26,...,30.599926,0.223356,10.313385,0.731847,0.611731,0.044557,1.119392,5.684665,217.660000,0.253698
13,12,F,19,2,5,2.571,5.00,822.00,250,101484.88,...,29.417252,0.241639,12.394800,0.592702,0.553313,0.050711,1.147071,5.049404,201.408000,0.245022
14,13,F,19,1,2,1.143,1.50,580.20,102,7907.19,...,31.148542,0.174843,4.073586,1.003611,0.605338,0.039304,1.224519,4.358042,204.996000,0.353320
15,13,F,19,2,5,2.429,3.25,718.35,107,13350.23,...,30.628185,0.195769,3.822214,0.886949,0.624366,0.038793,1.174556,4.494803,232.580000,0.323770
16,14,F,24,1,4,1.000,3.00,877.48,360,30949.27,...,32.947807,0.293781,18.837349,0.785724,0.769601,0.049522,1.080602,5.873515,295.584000,0.336856
17,14,F,24,2,3,1.000,3.00,914.74,239,39453.10,...,32.899380,0.274127,16.711039,0.945111,0.774443,0.044726,1.142981,5.424971,336.452000,0.367812
18,15,M,29,1,3,1.143,1.50,850.13,177,52409.46,...,26.108562,0.225210,9.718151,1.260274,0.680033,0.065184,1.367868,1.685363,257.208000,0.302551
19,15,M,29,2,4,2.143,1.00,654.78,273,77535.20,...,26.025434,0.227531,10.165171,1.240436,0.728733,0.065319,1.393540,1.508484,202.572000,0.309374
20,16,F,24,1,3,1.286,1.75,1098.70,333,34750.51,...,30.708815,0.300741,16.994879,0.519230,0.677153,0.042705,1.101984,5.396425,291.752000,0.265543
21,16,F,24,2,5,2.286,3.25,907.17,227,25745.55,...,29.864685,0.292519,16.358644,0.487614,0.710814,0.049898,1.186276,4.894445,182.504000,0.201179
22,17,M,19,1,3,1.286,1.00,476.37,191,17151.18,...,23.596392,0.142234,3.804144,0.793783,0.640797,0.038408,1.238713,2.776398,286.856000,0.602171
23,17,M,19,2,4,2.571,3.00,607.58,166,18727.74,...,22.898533,0.185235,4.204899,0.789264,0.652370,0.044534,1.219478,2.512741,301.504000,0.496238
24,18,M,32,1,2,1.714,1.75,432.55,211,17499.96,...,20.691692,0.231923,9.315437,0.443832,0.804697,0.066094,1.510358,-0.221005,48.032000,0.111044
25,18,M,32,2,4,2.571,2.25,415.85,154,8320.21,...,20.158566,0.225724,9.701998,0.417781,0.951059,0.053759,1.452116,-0.455822,47.684000,0.114666
26,19,M,35,1,1,1.000,1.25,435.40,142,20296.09,...,21.033289,0.151416,3.637751,0.736191,0.795677,0.042132,1.279819,1.158130,127.152000,0.292035
27,19,M,35,2,4,1.286,1.25,786.98,171,18169.60,...,21.185181,0.156719,3.699112,0.773481,0.688509,0.039869,1.354707,0.884539,220.868000,0.280653
28,20,M,18,1,4,1.143,2.25,878.54,244,34659.36,...,20.662533,0.149699,3.302004,0.861510,0.796524,0.040522,1.410255,0.465082,291.272000,0.331541
29,20,M,18,2,2,2.143,4.00,891.90,213,30869.12,...,20.314421,0.175828,4.117388,0.771147,0.844649,0.045317,1.467904,0.004770,195.584000,0.219289
30,21,M,18,1,1,1.000,2.50,917.70,95,24277.74,...,22.353214,0.212561,4.574043,0.595735,0.589087,0.042278,1.199249,1.663383,237.040000,0.258298
31,21,M,18,2,4,2.429,3.75,1087.92,44,2941.43,...,22.581732,0.244603,8.376944,0.644479,0.670563,0.045296,1.162093,1.916158,373.460000,0.343279
32,22,F,23,1,4,1.000,2.50,743.96,110,17929.51,...,26.858553,0.344460,20.430992,0.448913,0.623306,0.073082,1.275392,3.236748,155.692000,0.209275
33,22,F,23,2,5,1.286,3.25,719.42,126,15113.46,...,26.425158,0.330872,18.847275,0.445592,0.666470,0.081686,1.384284,2.520407,226.020000,0.314170
34,23,M,21,1,3,1.000,2.25,839.72,140,38303.81,...,24.041595,0.260213,10.750614,0.619476,0.683413,0.051171,1.424515,1.869804,249.736000,0.297404
35,23,M,21,2,3,1.429,3.00,835.11,147,23724.51,...,23.896124,0.244368,9.792522,0.585159,0.709359,0.053296,1.426990,1.609973,234.924000,0.281309
36,25,F,27,1,3,1.571,1.50,656.46,99,10448.03,...,24.411863,0.345240,18.222401,0.584770,1.149224,0.071360,1.439994,-0.478097,129.048000,0.196582
37,25,F,27,2,4,3.143,3.25,724.80,89,18532.72,...,24.800882,0.323857,17.236589,0.609470,0.990790,0.068000,1.421068,0.017462,138.908000,0.191650
38,26,F,25,1,4,1.571,1.25,816.80,209,28521.24,...,28.774448,0.335353,20.151150,0.543508,0.891313,0.056262,1.126012,3.183834,203.440000,0.249070
39,26,F,25,2,2,1.143,2.25,654.94,64,12474.56,...,28.905535,0.334247,20.158619,0.579800,0.835913,0.056924,1.157757,2.930987,217.604000,0.332250
40,28,M,26,1,4,1.571,2.00,884.19,211,235824.64,...,22.264029,0.218172,6.174887,0.613379,0.840635,0.053447,1.430695,0.606821,209.436000,0.236868
41,28,M,26,2,3,2.429,3.25,924.91,111,154697.10,...,23.224911,0.219852,6.104130,0.892084,0.825766,0.051028,1.317505,1.666690,356.604000,0.385555
42,29,M,26,1,2,1.286,1.00,822.03,217,90237.53,...,25.780945,0.227690,9.551172,0.844055,0.755524,0.055761,1.491307,1.813639,354.332000,0.431045
43,29,M,26,2,4,1.000,1.00,771.04,222,40923.65,...,25.164005,0.241694,10.153011,0.788230,0.775756,0.062113,1.492809,1.285319,269.824000,0.349948
44,30,F,22,1,3,1.571,1.75,911.42,154,32197.98,...,31.776140,0.274446,15.634323,0.540869,0.614865,0.046142,1.081691,6.036354,371.728000,0.407856
45,30,F,22,2,2,1.286,1.50,891.95,133,19109.62,...,30.954948,0.281182,16.241459,0.556722,0.595366,0.052870,1.143158,5.159524,389.808000,0.437029
46,31,F,25,1,1,1.000,1.75,912.09,105,64819.34,...,26.948984,0.349573,20.766712,0.519329,0.845812,0.065491,1.389496,1.511305,123.924000,0.135868
47,31,F,25,2,4,2.429,3.50,1111.55,197,63777.09,...,28.644676,0.318270,18.928366,0.527932,0.765093,0.055971,1.290159,3.189396,236.452000,0.212723
48,32,F,36,1,3,1.429,2.75,642.52,143,35903.51,...,29.062328,0.277821,14.194555,0.768675,0.827111,0.039574,1.106338,4.239407,177.820000,0.276754
49,32,F,36,2,5,3.714,4.50,558.34,73,19436.69,...,27.588448,0.314810,17.896519,0.628653,0.927738,0.044228,1.203943,2.687398,102.812000,0.184139